/*----- PROTECTED REGION ID(FakeStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        FakeStateMachine.cpp
//
// description : State machine file for the Fake class
//
// project :     Fake
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Fake.h>

/*----- PROTECTED REGION END -----*/	//	Fake::FakeStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Fake_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(Fake::FakeStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Fake::FakeStateAllowed.AdditionalMethods

}	//	End of namespace
